### ISSUE TITLE
[BUG] Mediatemple mirror is dead

### ISSUE THREAD

**Issue by hegyre** [saltstack-formulas/remi-formula#15]
### Formula commit hash / release tag
[2497b60](https://github.com/saltstack-formulas/remi-formula/commit/2497b602d37b249605f7489fd79d0cb99e60224a)

### Versions reports (master & minion)
Salt v2017.7.2 (masterless)

### Describe the bug

Current mirror used in formula is dead.

```
----------
          ID: install_remi_rpm
    Function: pkg.installed
      Result: False
     Comment: An error was encountered while installing package(s): Error: HTTP 599: Timeout reading http://mirrors.mediatemple.net/remi/enterprise/remi-release-7.rpm
     Started: 16:41:12.178515
    Duration: 31391.096 ms
     Changes:

```

### Steps to reproduce the bug
Install remi release via formula.

### Expected behaviour
Repo is installed.

### Attempts to fix the bug
Use official link provided by remi:
https://rpms.remirepo.net/enterprise/remi-release-{5/6/7/8}.rpm
